ros_ign_interfaces/Entity collision1        # contact collision1
ros_ign_interfaces/Entity collision2        # contact collision2
geometry_msgs/Vector3[] positions           # list of contact position
geometry_msgs/Vector3[] normals             # list of contact normals
float64[] depths                            # list of penetration depths
geometry_msgs/Wrench[] wrenches             # list of forces/torques
