ros_ign_interfaces/Entity collision1        # Contact collision1
ros_ign_interfaces/Entity collision2        # Contact collision2
geometry_msgs/Vector3[] positions           # List of contact position
geometry_msgs/Vector3[] normals             # List of contact normals
float64[] depths                            # List of penetration depths
ros_ign_interfaces/JointWrench[] wrenches   # List of joint wrenches including forces/torques
