string name                 # Entity's scoped name.
geometry_msgs/Pose pose     
---
bool success                # Return true if spawned successfully.
string status_message       # Comments if available.