#!/bin/bash
set -ev

# No interactive dialogs.
export DEBIAN_FRONTEND=noninteractive

echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-prerelease bionic main" > /etc/apt/sources.list.d/gazebo-prerelease.list
apt-get install -qq -y wget
sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | apt-key add -
apt-get update -qq
apt-get install -qq -y python-rosdep python-catkin-tools
rosdep init
rosdep update
rosdep install --from-paths ./ -i -y --rosdistro melodic
apt-get install -qq -y libignition-common3-dev libignition-transport6-dev locate

# Configuration.
export CATKIN_WS=~/catkin_ws
export CATKIN_WS_SRC=${CATKIN_WS}/src

# Testing
updatedb
locate setup.bash

# Create ROS workspace and compile our package.
source /opt/ros/melodic/setup.bash
mkdir -p $CATKIN_WS_SRC
ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
cd $CATKIN_WS
catkin init
catkin config --install
catkin build --limit-status-rate 0.1 --no-notify -DCMAKE_BUILD_TYPE=Release
catkin build --limit-status-rate 0.1 --no-notify --make-args tests
catkin run_tests
