# Depth Camera bridge configuration.
- topic_name: "/depth_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  lazy: true
  publish_optical_frame: true
  direction: GZ_TO_ROS

- topic_name: "/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  publish_optical_frame: true
  lazy: true
  direction: GZ_TO_ROS

- topic_name: "/depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  lazy: true
  direction: GZ_TO_ROS
