- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/robot1_ns/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  frame_id: "map"
  child_frame_id: "robot1/base_link"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/robot2_ns/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  frame_id: "map"
  child_frame_id: "robot2/base_link"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/robot3_ns/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  frame_id: "map"
  child_frame_id: "robot3/base_link"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/robot4_ns/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  frame_id: "map"
  child_frame_id: "robot4/base_link"
  direction: GZ_TO_ROS
