model {
  file: "model.sdf"
}
name: "Google_Cardboard_Original_package"
description: "Google Cardboard Original (package)"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Google"
}
annotations {
  key: "mpn"
  value: "gcbogp"
}
annotations {
  key: "sku"
  value: "GCBOGP"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
